name: Linting, testing building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline-fe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        #   run: npm run build:prod
        # - name: lint typescript
        run: npm run lint:ts
      - name: lint css
        run: npm run lint:scss
      - name: run unit tests
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: rub visual tests
        run: npm run test:ui:ci
